import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("scale-positions", "routes/scale-positions.tsx"),
  route("lick-stash", "routes/lick-stash.tsx"),
  route("lick-stash/:packSlug", "routes/lick-stash-pack.tsx"),
  route("pentatonic-triads", "routes/pentatonic-triads.tsx"),
  route("pentatonic-colors", "routes/pentatonic-colors.tsx"),
  route("interval-shapes", "routes/interval-shapes.tsx"),
  route("shape-explorer", "routes/shape-explorer.tsx"),
  route("chord-voicings", "routes/chord-voicings.tsx"),
  route("arpeggio-maps", "routes/arpeggio-maps.tsx"),
  route("circle-of-fifths", "routes/circle-of-fifths.tsx"),
  route("wylde-scales", "routes/wylde-scales.tsx"),
  route("yngwie-scales", "routes/yngwie-scales.tsx"),
  route("scale-builder", "routes/scale-builder.tsx"),
  route("chord-tones", "routes/chord-tones.tsx"),
  route("note-recognition", "routes/note-recognition.tsx"),
  route("staff-notes", "routes/staff-notes.tsx"),
  route("morning-coffee", "routes/morning-coffee.tsx"),
  route("pentatonic-practice", "routes/pentatonic-practice.tsx"),
  route("metronome", "routes/metronome.tsx"),
  route("practice-log", "routes/practice-log.tsx"),
] satisfies RouteConfig;
